/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "Vuepress基本配置",
  "description": "MYDOCS",
  "base": "/",
  "headTags": [
    [
      "meta",
      {
        "name": "theme-color",
        "content": "#3eaf7c"
      }
    ],
    [
      "meta",
      {
        "name": "apple-mobile-web-app-capable",
        "content": "yes"
      }
    ],
    [
      "meta",
      {
        "name": "apple-mobile-web-app-status-bar-style",
        "content": "black"
      }
    ]
  ],
  "pages": [
    {
      "title": "Config",
      "frontmatter": {
        "sidebar": "auto"
      },
      "regularPath": "/config/",
      "relativePath": "config/README.md",
      "key": "v-9d1331d6",
      "path": "/config/",
      "headers": [
        {
          "level": 2,
          "title": "foo",
          "slug": "foo"
        },
        {
          "level": 2,
          "title": "bar",
          "slug": "bar"
        }
      ]
    },
    {
      "title": "更多信息",
      "frontmatter": {},
      "regularPath": "/guide/hedo.html",
      "relativePath": "guide/hedo.md",
      "key": "v-7b1f2452",
      "path": "/guide/hedo.html"
    },
    {
      "title": "Introduction",
      "frontmatter": {},
      "regularPath": "/guide/",
      "relativePath": "guide/README.md",
      "key": "v-095370f6",
      "path": "/guide/",
      "headers": [
        {
          "level": 2,
          "title": "max",
          "slug": "max"
        },
        {
          "level": 3,
          "title": "remi",
          "slug": "remi"
        }
      ]
    },
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "https://v1.vuepress.vuejs.org/hero.png",
        "tagline": "MYDOCS",
        "actionText": "Quick Start →",
        "actionLink": "/guide/",
        "features": [
          {
            "title": "Feature 1 Title",
            "details": "Feature 1 Description"
          },
          {
            "title": "Feature 2 Title",
            "details": "Feature 2 Description"
          },
          {
            "title": "Feature 3 Title",
            "details": "Feature 3 Description"
          }
        ],
        "footer": "Made by ke with ❤️"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-37b9621c",
      "path": "/"
    },
    {
      "title": "Using Vue in Markdown",
      "frontmatter": {},
      "regularPath": "/guide/using-vue.html",
      "relativePath": "guide/using-vue.md",
      "key": "v-0afca6c8",
      "path": "/guide/using-vue.html",
      "headers": [
        {
          "level": 2,
          "title": "Browser API Access Restrictions",
          "slug": "browser-api-access-restrictions"
        },
        {
          "level": 2,
          "title": "",
          "slug": ""
        }
      ]
    }
  ],
  "themeConfig": {
    "repo": "",
    "editLinks": false,
    "docsDir": "",
    "editLinkText": "",
    "lastUpdated": false,
    "nav": [
      {
        "text": "教程",
        "link": "/guide/"
      },
      {
        "text": "设计思路",
        "link": "/config/"
      },
      {
        "text": "github",
        "link": "https://v1.vuepress.vuejs.org"
      }
    ],
    "sidebar": {
      "/guide/": [
        {
          "title": "教程",
          "collapsable": false,
          "children": [
            "",
            "using-vue",
            "hedo"
          ]
        }
      ]
    }
  }
}