/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "C:\\Users\\GDXY-002\\Desktop\\blog\\node_modules\\@vuepress\\theme-blog\\layouts\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-592f7944",
    path: "/2018/11/07/frontmatter-in-vuepress-2/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Post", "v-592f7944").then(next)
    },
  },
  {
    path: "/2018/11/07/frontmatter-in-vuepress-2/index.html",
    redirect: "/2018/11/07/frontmatter-in-vuepress-2/"
  },
  {
    path: "/_posts/2018-11-7-frontmatter-in-vuepress-2.html",
    redirect: "/2018/11/07/frontmatter-in-vuepress-2/"
  },
  {
    name: "v-f322c4e4",
    path: "/2018/11/07/frontmatter-in-vuepress/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Post", "v-f322c4e4").then(next)
    },
  },
  {
    path: "/2018/11/07/frontmatter-in-vuepress/index.html",
    redirect: "/2018/11/07/frontmatter-in-vuepress/"
  },
  {
    path: "/_posts/2018-11-7-frontmatter-in-vuepress.html",
    redirect: "/2018/11/07/frontmatter-in-vuepress/"
  },
  {
    name: "v-e3899034",
    path: "/2019/02/26/markdown-slot-3/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Post", "v-e3899034").then(next)
    },
  },
  {
    path: "/2019/02/26/markdown-slot-3/index.html",
    redirect: "/2019/02/26/markdown-slot-3/"
  },
  {
    path: "/_posts/2019-2-26-markdown-slot-3.html",
    redirect: "/2019/02/26/markdown-slot-3/"
  },
  {
    name: "v-f5bdabb0",
    path: "/2019/02/26/markdown-slot-2/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Post", "v-f5bdabb0").then(next)
    },
  },
  {
    path: "/2019/02/26/markdown-slot-2/index.html",
    redirect: "/2019/02/26/markdown-slot-2/"
  },
  {
    path: "/_posts/2019-2-26-markdown-slot-2.html",
    redirect: "/2019/02/26/markdown-slot-2/"
  },
  {
    name: "v-ee86277c",
    path: "/2018/11/07/frontmatter-in-vuepress-3/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Post", "v-ee86277c").then(next)
    },
  },
  {
    path: "/2018/11/07/frontmatter-in-vuepress-3/index.html",
    redirect: "/2018/11/07/frontmatter-in-vuepress-3/"
  },
  {
    path: "/_posts/2018-11-7-frontmatter-in-vuepress-3.html",
    redirect: "/2018/11/07/frontmatter-in-vuepress-3/"
  },
  {
    name: "v-d15574b8",
    path: "/2019/02/26/markdown-slot-4/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Post", "v-d15574b8").then(next)
    },
  },
  {
    path: "/2019/02/26/markdown-slot-4/index.html",
    redirect: "/2019/02/26/markdown-slot-4/"
  },
  {
    path: "/_posts/2019-2-26-markdown-slot-4.html",
    redirect: "/2019/02/26/markdown-slot-4/"
  },
  {
    name: "v-6c5ef30c",
    path: "/2019/05/06/writing-a-vuepress-theme-2/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Post", "v-6c5ef30c").then(next)
    },
  },
  {
    path: "/2019/05/06/writing-a-vuepress-theme-2/index.html",
    redirect: "/2019/05/06/writing-a-vuepress-theme-2/"
  },
  {
    path: "/_posts/2019-5-6-writing-a-vuepress-theme-2.html",
    redirect: "/2019/05/06/writing-a-vuepress-theme-2/"
  },
  {
    name: "v-0d440d10",
    path: "/2019/05/06/writing-a-vuepress-theme-3/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Post", "v-0d440d10").then(next)
    },
  },
  {
    path: "/2019/05/06/writing-a-vuepress-theme-3/index.html",
    redirect: "/2019/05/06/writing-a-vuepress-theme-3/"
  },
  {
    path: "/_posts/2019-5-6-writing-a-vuepress-theme-3.html",
    redirect: "/2019/05/06/writing-a-vuepress-theme-3/"
  },
  {
    name: "v-46456632",
    path: "/2019/02/26/markdown-slot/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Post", "v-46456632").then(next)
    },
  },
  {
    path: "/2019/02/26/markdown-slot/index.html",
    redirect: "/2019/02/26/markdown-slot/"
  },
  {
    path: "/_posts/2019-2-26-markdown-slot.html",
    redirect: "/2019/02/26/markdown-slot/"
  },
  {
    name: "v-28eb6c76",
    path: "/2019/05/06/writing-a-vuepress-theme-4/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Post", "v-28eb6c76").then(next)
    },
  },
  {
    path: "/2019/05/06/writing-a-vuepress-theme-4/index.html",
    redirect: "/2019/05/06/writing-a-vuepress-theme-4/"
  },
  {
    path: "/_posts/2019-5-6-writing-a-vuepress-theme-4.html",
    redirect: "/2019/05/06/writing-a-vuepress-theme-4/"
  },
  {
    name: "v-0b44b304",
    path: "/2019/05/06/writing-a-vuepress-theme/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Post", "v-0b44b304").then(next)
    },
  },
  {
    path: "/2019/05/06/writing-a-vuepress-theme/index.html",
    redirect: "/2019/05/06/writing-a-vuepress-theme/"
  },
  {
    path: "/_posts/2019-5-6-writing-a-vuepress-theme.html",
    redirect: "/2019/05/06/writing-a-vuepress-theme/"
  },
  {
    name: "v-b2754d56",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-b2754d56").then(next)
    },
    meta: {"pid":"post","id":"post"}
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-b1564aac",
    path: "/tag/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("FrontmatterKey", "v-b1564aac").then(next)
    },
    meta: {"pid":"tag","id":"tag"}
  },
  {
    path: "/tag/index.html",
    redirect: "/tag/"
  },
  {
    name: "v-8fdafa70",
    path: "/page/2/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-8fdafa70").then(next)
    },
    meta: {"pid":"post","id":"post"}
  },
  {
    path: "/page/2/index.html",
    redirect: "/page/2/"
  },
  {
    name: "v-8fdafa32",
    path: "/page/3/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-8fdafa32").then(next)
    },
    meta: {"pid":"post","id":"post"}
  },
  {
    path: "/page/3/index.html",
    redirect: "/page/3/"
  },
  {
    path: '*',
    component: GlobalLayout
  }
]