/**
 * Generated by "@vuepress/plugin-blog"
 */

import sorters from './pageSorters'
import filters from './pageFilters'

export default [{
  pid: "post",
  id: "post",
  filter: filters.post,
  sorter: sorters.post,
  pages: [{"path":"/","interval":[0,4]},{"path":"/page/2/","interval":[5,9]},{"path":"/page/3/","interval":[10,11]}],
  prevText: "Prev",
  nextText: "Next",
}]